#!/usr/bin/env python3
"""Generate assets/js/country-centroids.js from a public country-centroid dataset.

Source data (MIT licensed):
  https://raw.githubusercontent.com/gavinr/world-countries-centroids/master/dist/countries.geojson
  (c) 2021 Gavin Rehkemper

Powers the country dot map on the home page: assets/js/dashboard.js looks up
each study's `country` string in the generated table to get a [lat, lon] to
plot. Re-run only if the source dataset changes:
    curl -sL <source url above> -o scripts/.country-centroids-src.geojson
    python3 scripts/generate_country_centroids.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "scripts" / ".country-centroids-src.geojson"
OUT = ROOT / "assets" / "js" / "country-centroids.js"


def main():
    data = json.loads(SRC.read_text())
    table = {}
    for feature in data["features"]:
        name = feature["properties"]["COUNTRY"]
        lon, lat = feature["geometry"]["coordinates"]
        table[name] = [round(lat, 2), round(lon, 2)]

    js = (
        "// Generated by scripts/generate_country_centroids.py — do not hand-edit.\n"
        "// Maps a country name (as coded in the dataset) to [lat, lon].\n"
        "window.HPT_COUNTRY_CENTROIDS = "
        + json.dumps(table, separators=(",", ":"), sort_keys=True)
        + ";\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(js)
    print(f"Wrote {OUT} ({len(table)} countries)")


if __name__ == "__main__":
    main()
